### ISSUE TITLE
Add fee structure breakdown with comparisons

### ISSUE THREAD

**Issue by d1ll0n** [indexed-finance/docs#17]
Add a page to the documentation explaining our fee structure, including exit fees and swap fees. Add a comparison table showing how Indexed compares to e.g. PieDAO, Index Coop, etc. (mint/burn/streaming fees)

**Comment by fnery** [comment]
I'll work on this

(EDIT: PR submitted - https://github.com/indexed-finance/docs/pull/19)

**Comment by laurenceday** [comment]
Merged PR #19
